sonar.projectKey=cost-share-next-js-app
sonar.projectName=cost-share-next-js-app
sonar.sources=src,lib
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true
sonar.qualitygate.wait=true
